import streamlit as st
from openai import OpenAI
import datetime
import requests

# 1. Ρύθμιση Σελίδας
st.set_page_config(page_title="ironbrick v9.4 | Educational Portal", page_icon="🎓", layout="wide")

# --- CSS ΓΙΑ ΕΠΑΓΓΕΛΜΑΤΙΚΟ IDE LOOK ---
st.markdown("""
    <style>
    header {visibility: hidden;} footer {visibility: hidden;}
    .stExpander { border: 1px solid #ddd; border-radius: 8px; background-color: #fafafa; }
    .stCodeBlock { border-radius: 8px; box-shadow: inset 0 1px 3px rgba(0,0,0,0.1); }
    </style>
    """, unsafe_allow_html=True)

# 2. Σύνδεση
try:
    client = OpenAI(base_url="[https://api.groq.com/openai/v1](https://api.groq.com/openai/v1)", api_key=st.secrets["GROQ_API_KEY"])
    SHEETDB_URL = st.secrets["GSHEET_URL"]
except:
    st.error("⚠️ Σφάλμα διαμόρφωσης περιβάλλοντος.")

# 3. Tabs
tab_app, tab_info, tab_data = st.tabs(["🚀 Εργαστήριο Προγραμματισμού", "📖 Πληροφορίες", "📂 Αρχείο"])

with tab_app:
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "last_code" not in st.session_state:
        st.session_state.last_code = ""

    col_in, col_out = st.columns([1, 1], gap="large")
    
    with col_in:
        with st.form(key='ide_form', clear_on_submit=True):
            u_id = st.text_input("ID Μαθητή:", value="Student_01")
            lang_choice = st.selectbox("Γλώσσα:", ["MicroPython", "Arduino C"])
            prompt = st.text_area("Περιγραφή Αποστολής:", placeholder="Π.χ. Κάνε το Maqueen να στρίψει δεξιά αν βρει εμπόδιο...", height=150)
            submit = st.form_submit_button("🔨 Κατασκευή Κώδικα")

    with col_out:
        if submit and prompt:
            st.session_state.messages.append({"role": "user", "content": prompt})
            with st.spinner('🛠️ Σύνθεση οδηγιών...'):
                try:
                    # ΑΥΣΤΗΡΟ ΠΡΩΤΟΚΟΛΛΟ ΓΙΑ ΑΠΟΦΥΓΗ AI ΙΧΝΩΝ
                    sys_prompt = (
                        f"Είσαι ο καθηγητής ρομποτικής. Δώσε ΜΟΝΟ τον καθαρό κώδικα {lang_choice}. "
                        "Μην χρησιμοποιείς Markdown blocks (```), μην βάζεις σχόλια 'Generated by AI', "
                        "μην δίνεις χαιρετισμούς. Δώσε ΜΟΝΟ τις εντολές προγραμματισμού."
                    )
                    
                    response = client.chat.completions.create(
                        model="llama-3.3-70b-versatile",
                        messages=[{"role": "system", "content": sys_prompt}] + st.session_state.messages
                    )
                    
                    # Καθαρισμός από τυχόν Markdown που ξέφυγε
                    clean_code = response.choices[0].message.content.replace("```python", "").replace("```cpp", "").replace("```", "").strip()
                    st.session_state.last_code = clean_code
                    st.session_state.messages.append({"role": "assistant", "content": clean_code})

                    st.markdown(f"#### ⚙️ Αρχείο: {lang_choice}")
                    st.code(clean_code, language='python' if lang_choice=="MicroPython" else 'cpp')
                    
                    # ΚΡΥΦΟ LOGGING
                    requests.post(SHEETDB_URL, json={
                        "data": [{
                            "Timestamp": str(datetime.datetime.now()),
                            "Student_ID": str(u_id),
                            "Language": str(lang_choice),
                            "Prompt": str(prompt),
                            "Answer": str(clean_code).replace('"', "'")
                        }]
                    })
                except:
                    st.error("⚠️ Αδυναμία σύνδεσης με τον εξυπηρετητή.")

    # --- ΕΚΠΑΙΔΕΥΤΙΚΗ ΕΠΕΞΗΓΗΣΗ ---
    if st.session_state.last_code:
        st.write("")
        with st.expander("📚 Ανάλυση Λειτουργίας (Καθηγητής)"):
            with st.spinner('Αναλύω τη λογική...'):
                # Prompt που επιβάλλει ανθρώπινο ύφος
                explain_msg = [
                    {"role": "system", "content": "Είσαι ο καθηγητής του μαθητή. Εξήγησε τις εντολές ΜΟΝΟ στα Ελληνικά. "
                                                 "Μην χρησιμοποιείς φράσεις όπως 'Ως μοντέλο γλώσσας' ή 'Αυτός ο κώδικας κάνει'. "
                                                 "Μίλα απευθείας στον μαθητή (π.χ. 'Εδώ ορίζουμε την ταχύτητα...')."},
                    {"role": "user", "content": f"Εξήγησε το πρόγραμμα:\n{st.session_state.last_code}"}
                ]
                exp_res = client.chat.completions.create(model="llama-3.3-70b-versatile", messages=explain_msg)
                st.write(exp_res.choices[0].message.content)

with tab_info:
    st.info("Ερευνητική Πλατφόρμα Προγραμματισμού Maqueen v9.4")

with tab_data:
    st.link_button("📊 Πρόσβαση στο Αρχείο Δεδομένων", st.secrets.get("GSHEET_URL_LINK", "#"))
